spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ourtube
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      location: E:/JavaProjects/ourtube/upload/videos/
